server:
    port: 9009
spring:
    datasource:
        continue-on-error: true
        initialization-mode: always
        initialize: true
        password: 'Manhattan99'
        username: postgres
        url: jdbc:postgresql://localhost:5432/SubmissionDB
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
