server:
  port: 9010
spring:
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # Locale used for formatting
    time-zone: "GMT+8"
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: 'Manhattan99'
    username: postgres
    url: jdbc:postgresql://localhost:5432/SubmissionDB
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
